name: Build Releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              npm run build -- --linux --x64
            elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
              npm run build -- --linux --arm64
            fi
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            npm run build -- --mac
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            npm run build -- --win
          fi

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
