name: Build Releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: |
          # For Ubuntu and macOS, use bash syntax
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]] || [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              npm run build -- --linux --x64
            elif [[ "${{ matrix.arch }}" == "arm64" ]]; then
              npm run build -- --linux --arm64
            fi
          fi
        shell: bash

      - name: Build Windows application
        if: matrix.os == 'windows-latest'
        run: |
          if ($env:matrix_arch -eq 'x64') {
            npm run build -- --win --x64
          } elseif ($env:matrix_arch -eq 'arm64') {
            npm run build -- --win --arm64
          }
        shell: pwsh

      - name: Create Git tag
        if: github.ref == 'refs/heads/main'
        run: |
          TAG_NAME="v${{ github.run_id }}"
          git tag -a "$TAG_NAME" -m "Automated release $TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $TAG_NAME
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
